CREATE TABLE IF NOT EXISTS users (
                                     user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     user_name      VARCHAR(111) NOT NULL,
                                     email          VARCHAR(111) NOT NULL,
                                     CONSTRAINT uq_user_email UNIQUE (email));

CREATE TABLE IF NOT EXISTS requests (
                                        request_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        description  VARCHAR(1111) NOT NULL,
                                        requester_id BIGINT REFERENCES users (user_id) ON DELETE CASCADE,
                                        created_date TIMESTAMP WITHOUT TIME ZONE NOT NULL);

CREATE TABLE IF NOT EXISTS items (
                                     item_id BIGINT     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
                                     item_name          VARCHAR(111) NOT NULL,
                                     description        VARCHAR(1111) NOT NULL,
                                     is_available       BOOLEAN NOT NULL,
                                     owner_id           BIGINT REFERENCES users (user_id) ON DELETE CASCADE,
                                     request_id         BIGINT REFERENCES requests (request_id) ON DELETE CASCADE);

CREATE TABLE IF NOT EXISTS bookings (
                                        booking_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
                                        start_date        TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                                        end_date          TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                                        item_id BIGINT    REFERENCES items (item_id) ON DELETE CASCADE,
                                        booker_id BIGINT  REFERENCES users (user_id) ON DELETE CASCADE,
                                        status            VARCHAR(10));

CREATE TABLE IF NOT EXISTS comments (
                                        comment_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        text              VARCHAR(1111) NOT NULL,
                                        item_id BIGINT    REFERENCES items (item_id) ON DELETE CASCADE,
                                        author_id         BIGINT REFERENCES users (user_id) ON DELETE CASCADE,
                                        created           TIMESTAMP WITHOUT TIME ZONE not null);
                                        
                                       
